spring.application.name=project
server.port=8082

spring.datasource.url=jdbc:h2:mem:complain_system_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=Y29tcGxhaW4tc3lzdGVtLWp3dC1zZWNyZXQtZm9yLWRldi0yMDI2LTA1LTIz
app.jwt.expiration-ms=86400000